repos:
  - repo: local
    hooks:
      - id: build
        name: Build Typst HTML
        entry: uv run scripts/build.py
        language: python
        pass_filenames: false
        additional_dependencies:
          - pyyaml
