repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.9
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: build
        name: Build Typst HTML
        entry: uv run scripts/build.py
        language: python
        pass_filenames: false
        additional_dependencies:
          - pyyaml
